#!/usr/bin/env python

from subprocess import Popen, PIPE
from time import sleep, strftime
import os, sys, hashlib

scons_git = os.path.basename(sys.argv[0]) == 'pre-commit'
if scons_git:
	# Break immediately if there's no changes
	if not Popen(['git', 'diff', 'HEAD', '--quiet'], env=dict()).wait(): sys.exit()
	scons_hash = hashlib.md5(open('setup.py').read()).hexdigest()\
		 if os.path.exists('setup.py') else ''

ver_minor = sum( 1 for i in Popen(['git', 'rev-list',
	'--since=%s'%strftime('01.%m.%Y'), 'master'], stdout=PIPE).stdout )

# Check for lame syntax errors
from string import whitespace as spaces
import py_compile
for src in ( line.strip(spaces) for line in
		Popen(['find', '-name', '*.py', '-print'], stdout=PIPE).stdout ):
	if src.endswith('.tpl.py'): continue # templates are, by definition, incomplete
	try: py_compile.compile(src, cfile='/dev/null', doraise=True)
	except py_compile.PyCompileError, err:
		print '{} (file: {}):\n\t{}'.format(err.exc_type_name, err.file, err.exc_value)
		sys.exit(1)

# Regenerate setup.py
open('setup.py', 'w').write(
	open('_setup.tpl.py').read().format(
		version=strftime('%y.%m.{}').lstrip('0').format(ver_minor),
		warning=( '# This script is generated by {} script,'
			' any changes to it will be lost' ).format(sys.argv[0]) ) )

if scons_git:
	# Check if no changes to scons were made and pass the commit
	if hashlib.md5(open('setup.py').read() ).hexdigest() == scons_hash: sys.exit(0)

	# Reindex new files in background
	if not os.fork():
		os.setsid()
		while True:
			if os.path.exists('.git/index.lock'): sleep(0.2)
			else: break
		Popen(['git', 'add', 'setup.py'], env=dict()).wait()
		sys.exit()

	print 'setup.py regenerated, re-initiate commit process manually'
	sys.exit(1) # Break commit sequence
